blank_issues_enabled: true
contact_links:
  - name: 📧 Contact student developer
    url: https://www.gla.ac.uk/schools/computing/staff/index.html/staffcontact/person/4edeefe68796
    about: Please send an email to get in contact.