name: Black style check

on:
  push:
    paths:
      - "**.py"
    branches:
      - develop
  pull_request:
    paths:
      - "**.py"
    branches:
      - develop

jobs:
  black_linter:
    name: Black formatter
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: rickstaa/action-black@v1
        with:
          black_args: ". --check"
