name: Compile Status Report

on:
  push:
    paths:
      - "docs/important/status.tex"

jobs:
  build-report:
    runs-on: ubuntu-latest
    name: Create document
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v3
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          root_file: status.tex
          working_directory: docs/important
      - name: Rename PDF
        run: |
          mv docs/important/status.pdf "Inesh Bose - Portion Mate (Status Report).pdf"
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: "Status Report"
          path: "Inesh Bose - Portion Mate (Status Report).pdf"
