name: Compile Dissertation

on:
  push:
    paths:
      - "dissertation/**"
      - "!dissertation/status.tex"

jobs:
  build-dissertation:
    runs-on: ubuntu-latest
    name: Create document
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v3
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          root_file: l4proj.tex
          latexmk_shell_escape: true
          working_directory: dissertation
          extra_system_packages: "inkscape"
      - name: Rename PDF
        run: |
          mv dissertation/l4proj.pdf "Inesh Bose - Portion Mate.pdf"
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: Dissertation
          path: "Inesh Bose - Portion Mate.pdf"
