name: Deploy Wiki

on:
  push:
    paths:
      - 'docs/**'
    branches:
      - develop

jobs:
  update-wiki:
    runs-on: ubuntu-latest
    name: Update wiki
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: Copy file
        run: |
          cp docs/index.md docs/Home.md
      - name: Upload Documentation to Wiki
        uses: SwiftDocOrg/github-wiki-publish-action@v1
        with:
          path: "docs"
        env:
          GH_PERSONAL_ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}