name: Deploy Wiki

on:
  push:
    paths:
      - 'docs/**'
    branches:
      - develop

jobs:
  update-wiki:
    runs-on: ubuntu-latest
    name: Update wiki
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: Copy file
        run: |
          cp docs/index.md docs/Home.md
      - name: List Sidebar
        run: |
          shopt -s extglob

          for folder in docs/!(archive|assets|env)/; do
              fname="${folder#*/}"
              name="${fname^}"
              echo "* ${name%?}" >> docs/_Sidebar.md
            for file in $folder*; do
              echo "  * [$(basename $file | sed 's/\.[^.]*$//')]($(basename $file | sed 's/\.[^.]*$//'))" >> docs/_Sidebar.md
            done
          done
      - name: Upload Documentation to Wiki
        uses: SwiftDocOrg/github-wiki-publish-action@v1
        with:
          path: "docs"
        env:
          GH_PERSONAL_ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}