name: ESLint/Prettier/Airbnb style check

on:
  push:
    paths:
      - "src/**/*.[jt]sx?"
    branches:
      - develop
  pull_request:
    paths:
      - "src/**/*.[jt]sx?"
    branches:
      - develop

jobs:
  check_linter:
    name: Check formatter
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install modules
        run: yarn
      - name: Run ESLint
        run: npx eslint src
