name: ESLint/Prettier/Airbnb style check

on:
  push:
    paths:
      - "**/*.js"
      - "**/*.ts"
      - "**/*.jsx"
      - "**/*.tsx"
    branches:
      - develop
  pull_request:
    paths:
      - "**/*.js"
      - "**/*.ts"
      - "**/*.jsx"
      - "**/*.tsx"
    branches:
      - develop

jobs:
  check_linter:
    name: Check formatter
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install modules
        run: yarn
      - name: Run ESLint
        run: npx eslint src
