name: Close PR to Master

on:
  pull_request:
    branches:
      - master

jobs:
  close:
    runs-on: ubuntu-latest
    if: ${{ github.ref != 'refs/heads/develop' }}
    steps:
      - name: Close Pull
        uses: peter-evans/close-pull@v1
        with:
          pull-request-number: ${{ github.event.number }}
          comment: Direct merge to master restricted.
          delete-branch: false
