name: Server code check

on:
  push:
    paths:
      - "src/**/*.py"
    branches:
      - develop
  pull_request:
    paths:
      - "src/**/*.py"
    branches:
      - develop

jobs:
  black_linter:
    name: Black formatter
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: rickstaa/action-black@v1
        with:
          black_args: ". --check"
  django_tests:
    name: Django tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ./src
      - name: Run test
        run: |
          python run.py migrate
          python run.py test main rest
